---
  - name: Configure SSH
    hosts: all
    gather_facts: no
    connection: local

    tasks:
      - debug: 
          msg: "The SSH crypto key generate will fail because of netmiko/ntc timeouts. Comment that out after it becomes no longer necessary."

    # this will fail the first time. When it's run once to get your keys, just comment it out.
    # coming soon - global_delay_factor will be available, but not yet.
      - ntc_config_command:
          connection: ssh
          platform: " {{ platform }}"
          port: "{{ port }}"
          commands:
            - ip domain-name mycooldomain.net
            - crypto key generate rsa modulus 2048
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          #global_delay_factor: 4
          
    # this will configure ssh parameters
      - ntc_config_command:
          connection: "{{ connection }}"
          platform: "{{ platform }}"
          port: "{{ port }}"
          commands:
            - ip ssh version 2
            - line vty 0 {{ max_vty }}
            - transport input ssh telnet
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
